[tool.poetry]
name = "reflex-exceptions"
version = "0.1.0"
description = ""
authors = ["Benedikt Bartscher <bb@senbax.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
